"""add challenge max_points, challenge_junior fields, activity links achieved_date, quiz_result answers

Revision ID: 018a366841e3
Revises: e14a9aaed29b
Create Date: 2026-04-09 19:49:19.680939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018a366841e3'
down_revision: Union[str, Sequence[str], None] = 'e14a9aaed29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('links', sa.JSON(), nullable=True))
    op.add_column('activities', sa.Column('achieved_date', sa.Date(), nullable=True))
    op.add_column('challenge_junior', sa.Column('comment', sa.String(length=2000), nullable=True))
    op.add_column('challenge_junior', sa.Column('links', sa.JSON(), nullable=True))
    op.add_column('challenge_junior', sa.Column('awarded_points', sa.Integer(), nullable=True))
    op.add_column('challenge_junior', sa.Column('feedback', sa.String(length=2000), nullable=True))
    op.add_column('challenges', sa.Column('max_points', sa.Integer(), nullable=True))
    op.add_column('quiz_results', sa.Column('answers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_results', 'answers')
    op.drop_column('challenges', 'max_points')
    op.drop_column('challenge_junior', 'feedback')
    op.drop_column('challenge_junior', 'awarded_points')
    op.drop_column('challenge_junior', 'links')
    op.drop_column('challenge_junior', 'comment')
    op.drop_column('activities', 'achieved_date')
    op.drop_column('activities', 'links')
    # ### end Alembic commands ###
