"""Fix models, add challenge_junior model

Revision ID: 38ca495b57af
Revises: cae77062bd3e
Create Date: 2026-02-26 01:02:32.150705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38ca495b57af'
down_revision: Union[str, Sequence[str], None] = 'cae77062bd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UPCOMING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='challenge_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'password_hash',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    op.drop_table('challenges')
    # ### end Alembic commands ###
