"""challenges statuses

Revision ID: 444052e0515b
Revises: e75d33636140
Create Date: 2026-04-04 19:18:21.809071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444052e0515b'
down_revision: Union[str, Sequence[str], None] = 'e75d33636140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    task_status_new = sa.Enum(
        'DRAFT',
        'UPCOMING',
        'ACTIVE',
        'COMPLETED',
        'CANCELLED',
        name='task_status_new',
    )
    task_status_new.create(op.get_bind(), checkfirst=True)

    op.execute(
        "ALTER TABLE activities ALTER COLUMN task_status TYPE task_status_new USING "
        "CASE task_status "
        "WHEN 'PENDING' THEN 'ACTIVE' "
        "WHEN 'APPROVED' THEN 'COMPLETED' "
        "WHEN 'REJECTED' THEN 'CANCELLED' "
        "WHEN 'REVISION' THEN 'ACTIVE' "
        "ELSE 'ACTIVE' END::text::task_status_new"
    )

    op.execute("DROP TYPE IF EXISTS task_status")
    op.execute("ALTER TYPE task_status_new RENAME TO task_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    task_status_old = sa.Enum(
        'PENDING',
        'APPROVED',
        'REJECTED',
        'REVISION',
        name='task_status_old',
    )
    task_status_old.create(op.get_bind(), checkfirst=True)

    op.execute(
        "ALTER TABLE activities ALTER COLUMN task_status TYPE task_status_old USING "
        "CASE task_status "
        "WHEN 'COMPLETED' THEN 'APPROVED' "
        "WHEN 'CANCELLED' THEN 'REJECTED' "
        "WHEN 'DRAFT' THEN 'PENDING' "
        "WHEN 'UPCOMING' THEN 'PENDING' "
        "WHEN 'ACTIVE' THEN 'PENDING' "
        "ELSE 'PENDING' END::text::task_status_old"
    )

    op.execute("DROP TYPE IF EXISTS task_status")
    op.execute("ALTER TYPE task_status_old RENAME TO task_status")
    # ### end Alembic commands ###
