"""remove challenge and calendar events relationships

Revision ID: 51172fd08647
Revises: 444052e0515b
Create Date: 2026-04-04 19:59:22.080231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51172fd08647'
down_revision: Union[str, Sequence[str], None] = '444052e0515b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Handle challenge_junior table
    op.add_column('challenge_junior', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('challenge_junior_challenge_id_fkey'), 'challenge_junior', type_='foreignkey')
    # Copy data from challenge_id to activity_id only for existing activity IDs
    op.execute('''
        UPDATE challenge_junior 
        SET activity_id = challenge_id 
        WHERE activity_id IS NULL 
        AND challenge_id IN (SELECT id FROM activities WHERE activity_type = 'TASK')
    ''')
    # Delete orphan records (challenge_id that don't have corresponding activities)
    op.execute('''
        DELETE FROM challenge_junior 
        WHERE activity_id IS NULL
    ''')
    # Make activity_id NOT NULL
    op.alter_column('challenge_junior', 'activity_id', nullable=False)
    # Create FK with NOT VALID option for PostgreSQL
    op.execute('''
        ALTER TABLE challenge_junior 
        ADD CONSTRAINT fk_challenge_junior_activity_id 
        FOREIGN KEY(activity_id) REFERENCES activities (id) ON DELETE CASCADE
        NOT VALID
    ''')
    op.execute('ALTER TABLE challenge_junior VALIDATE CONSTRAINT fk_challenge_junior_activity_id')
    op.drop_column('challenge_junior', 'challenge_id')
    
    # Handle meeting_attendance table
    op.add_column('meeting_attendance', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('meeting_attendance_event_id_fkey'), 'meeting_attendance', type_='foreignkey')
    # Copy data from event_id to activity_id only for existing activity IDs
    op.execute('''
        UPDATE meeting_attendance 
        SET activity_id = event_id 
        WHERE activity_id IS NULL 
        AND event_id IN (SELECT id FROM activities WHERE activity_type = 'EVENT')
    ''')
    # Delete orphan records (event_id that don't have corresponding activities)
    op.execute('''
        DELETE FROM meeting_attendance 
        WHERE activity_id IS NULL
    ''')
    # Make activity_id NOT NULL
    op.alter_column('meeting_attendance', 'activity_id', nullable=False)
    # Create FK with NOT VALID option for PostgreSQL
    op.execute('''
        ALTER TABLE meeting_attendance 
        ADD CONSTRAINT fk_meeting_attendance_activity_id 
        FOREIGN KEY(activity_id) REFERENCES activities (id) ON DELETE CASCADE
        NOT VALID
    ''')
    op.execute('ALTER TABLE meeting_attendance VALIDATE CONSTRAINT fk_meeting_attendance_activity_id')
    op.drop_column('meeting_attendance', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_attendance', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meeting_attendance', type_='foreignkey')
    op.create_foreign_key(op.f('meeting_attendance_event_id_fkey'), 'meeting_attendance', 'calendar_events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('meeting_attendance', 'activity_id')
    op.add_column('challenge_junior', sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'challenge_junior', type_='foreignkey')
    op.create_foreign_key(op.f('challenge_junior_challenge_id_fkey'), 'challenge_junior', 'challenges', ['challenge_id'], ['id'], ondelete='CASCADE')
    op.drop_column('challenge_junior', 'activity_id')
    # ### end Alembic commands ###
