"""refresh token

Revision ID: 728de791fcff
Revises: efa1ccb55653
Create Date: 2026-04-28 13:41:04.336081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728de791fcff'
down_revision: Union[str, Sequence[str], None] = 'efa1ccb55653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.drop_constraint(op.f('activities_challenge_id_fkey'), 'activities', type_='foreignkey')
    op.drop_constraint(op.f('activities_calendar_event_id_fkey'), 'activities', type_='foreignkey')
    op.drop_column('activities', 'calendar_event_id')
    op.drop_column('activities', 'challenge_id')
    op.drop_constraint(op.f('calendar_events_user_id_fkey'), 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'user_id')
    op.drop_column('calendar_events', 'requested_points')
    op.drop_constraint(op.f('challenges_user_id_fkey'), 'challenges', type_='foreignkey')
    op.drop_column('challenges', 'user_id')
    op.drop_column('challenges', 'requested_points')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('challenges', sa.Column('requested_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('challenges', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('challenges_user_id_fkey'), 'challenges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('calendar_events', sa.Column('requested_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('calendar_events', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('calendar_events_user_id_fkey'), 'calendar_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('activities', sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('calendar_event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('activities_calendar_event_id_fkey'), 'activities', 'calendar_events', ['calendar_event_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('activities_challenge_id_fkey'), 'activities', 'challenges', ['challenge_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
