"""knowledge base attachments

Revision ID: a62da1b4aa1f
Revises: 3e971071298e
Create Date: 2026-04-28 23:48:08.627669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62da1b4aa1f'
down_revision: Union[str, Sequence[str], None] = '3e971071298e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_articles', sa.Column('attachments', sa.JSON(), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_articles', 'attachments')
    # ### end Alembic commands ###
