"""Add mentor_junior model

Revision ID: cae77062bd3e
Revises: cc7b9f711663
Create Date: 2026-02-25 23:09:24.373093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae77062bd3e'
down_revision: Union[str, Sequence[str], None] = 'cc7b9f711663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_junior',
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('junior_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['junior_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mentor_id', 'junior_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentor_junior')
    # ### end Alembic commands ###
