"""challenges and events as differente activity types

Revision ID: e75d33636140
Revises: e14a9aaed29b
Create Date: 2026-04-04 19:09:07.150762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e75d33636140'
down_revision: Union[str, Sequence[str], None] = 'e14a9aaed29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    task_status_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVISION', name='task_status')
    task_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('activities', sa.Column('task_status', task_status_enum, nullable=True))
    event_status_enum = sa.Enum('SCHEDULED', 'ONGOING', 'COMPLETED', 'CANCELLED', name='event_status')
    event_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('activities', sa.Column('event_status', event_status_enum, nullable=True))
    op.add_column('activities', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('activities', sa.Column('url', sa.String(length=500), nullable=True))
    event_type_enum = sa.Enum('CHALLENGE', 'MEETING', 'DEADLINE', name='event_type')
    event_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('activities', sa.Column('event_type', event_type_enum, nullable=True))
    op.add_column('activities', sa.Column('challenge_id', sa.Integer(), nullable=True))
    op.alter_column('activities', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activities', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.drop_column('activities', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'REVISION', name='activity_status'), autoincrement=False, nullable=False))
    op.alter_column('activities', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('activities', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('activities', 'challenge_id')
    op.drop_column('activities', 'event_type')
    op.drop_column('activities', 'url')
    op.drop_column('activities', 'date')
    op.drop_column('activities', 'event_status')
    op.drop_column('activities', 'task_status')
    # ### end Alembic commands ###
