"""empty message

Revision ID: f973559c9dca
Revises: 752c27910b31
Create Date: 2026-03-05 00:52:22.636637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f973559c9dca'
down_revision: Union[str, Sequence[str], None] = '752c27910b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_junior', sa.Column('assigned_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mentor_junior', 'users', ['assigned_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentor_junior', type_='foreignkey')
    op.drop_column('mentor_junior', 'assigned_by')
    # ### end Alembic commands ###
